"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerAllIpc = registerAllIpc;
const tabs_1 = require("./tabs");
const omnibox_1 = require("./omnibox");
const settings_1 = require("./settings");
const actions_1 = require("./actions");
const userchrome_1 = require("./userchrome");
const screenshot_1 = require("./screenshot");
const downloads_1 = require("./downloads");
const adblock_1 = require("./adblock");
const torrent_1 = require("./torrent");
const video_1 = require("./video");
const bookmarks_1 = require("./bookmarks");
const history_1 = require("./history");
const windows_1 = require("./windows");
const userscript_1 = require("./userscript");
const policy_1 = require("./policy");
const workspace_1 = require("./workspace");
const password_1 = require("./password");
const data_1 = require("./data");
const tokens_1 = require("./tokens");
const macro_1 = require("./macro");
const mod_1 = require("./mod");
const system_1 = require("./system");
const extensions_1 = require("./extensions");
const update_1 = require("./update");
const perf_1 = require("./perf");
const find_1 = require("./find");
const widgets_1 = require("./widgets");
const groups_1 = require("./groups");
const readlater_1 = require("./readlater");
const permissions_1 = require("./permissions");
const sitedata_1 = require("./sitedata");
const import_1 = require("./import");
const ai_1 = require("./ai");
function registerAllIpc() {
    (0, windows_1.registerWindowsIpc)();
    (0, workspace_1.registerWorkspaceIpc)();
    (0, userscript_1.registerUserscriptIpc)();
    (0, policy_1.registerPolicyIpc)();
    (0, password_1.registerPasswordIpc)();
    (0, tabs_1.registerTabsIpc)();
    (0, omnibox_1.registerOmniboxIpc)();
    (0, settings_1.registerSettingsIpc)();
    (0, actions_1.registerActionsIpc)();
    (0, userchrome_1.registerUserChromeIpc)();
    (0, screenshot_1.registerScreenshotIpc)();
    (0, downloads_1.registerDownloadsIpc)();
    (0, adblock_1.registerAdblockIpc)();
    (0, torrent_1.registerTorrentIpc)();
    (0, video_1.registerVideoIpc)();
    (0, bookmarks_1.registerBookmarksIpc)();
    (0, history_1.registerHistoryIpc)();
    (0, data_1.registerDataIpc)();
    (0, tokens_1.registerTokensIpc)();
    (0, macro_1.registerMacroIpc)();
    (0, mod_1.registerModIpc)();
    (0, system_1.registerSystemIpc)();
    (0, extensions_1.registerExtensionsIpc)();
    (0, update_1.registerUpdateIpc)();
    (0, perf_1.registerPerfIpc)();
    (0, find_1.registerFindIpc)();
    (0, widgets_1.registerWidgetsIpc)();
    (0, groups_1.registerGroupsIpc)();
    (0, readlater_1.registerReadLaterIpc)();
    (0, permissions_1.registerPermissionsIpc)();
    (0, sitedata_1.registerSiteDataIpc)();
    (0, import_1.registerImportIpc)();
    (0, ai_1.registerAiIpc)();
}
